spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:~/testdb;
      username: sa
      driver-class-name: org.h2.Driver
      password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

